# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxVXPEl67cLdbE_OV8FY-jhqTLT7oUkn
"""

import pandas as pd
import seaborn as sns
import numpy as np

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns = data.feature_names)
data

df

from sklearn.model_selection import train_test_split
x = data['data']
y = data['target']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state=42)

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn import
dt1 = DecisionTreeClassifier()
dt1.fit(x_train, y_train)
treepredict1 = dt1.predict(x_test)

tree_para = {'criterion':['gini','entropy'],'max_depth':[4,5,6,7,8,9,10,11,12,15,20,30,40,50,70,90,120,150], 'splitter':['best', 'random']}
dt2 = GridSearchCV(DecisionTreeClassifier(), tree_para, cv=5)
# cv = cross validation - creates a specific number of subsets of the data, runs the model through all those subsets and then takes the average score of all the predictions
dt2.fit(x_train, y_train)
treepredict2 = dt2.predict(x_test)
print(dt2.best_params_)
print(dt2.best_score_)

from sklearn.metrics import accuracy_score
acc1 = accuracy_score(y_test, treepredict1)
acc2 = accuracy_score(y_test, treepredict2)
print(acc1)
print(acc2)

































